# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'AnyCPU'
  buildConfiguration: 'Release'

steps:
- task: file-creator@5
  inputs:
    fileoverwrite: true
    filepath: './Limbs.Web/PrivateSettings.config'
    filecontent: '<?xml version="1.0"?>
      <appSettings>
        <add key="Storage.ConnectionString" value="UseDevelopmentStorage=true" />
        <add key="Mail.Server" value="" />
        <add key="Mail.From" value="" />
        <add key="Mail.Username" value="" />
        <add key="Mail.Password" value="" />
        <add key="Google.Analytics.TrackingCodes" value="" />
        <add key="Google.Maps.Key" value="" />
        <add key="Google.Recaptcha.PublicKey" value="" />
        <add key="Google.Recaptcha.SecretKey" value="" />
        <add key="Facebook.AppId" value="" />
        <add key="Facebook.AppSecret" value="" />
        <add key="AdminEmails" value="" />
        <add key="Environment" value="dev" />
        <add key="webpages:Version" value="3.0.0.0" />
        <add key="webpages:Enabled" value="false" />
        <add key="ClientValidationEnabled" value="true" />
        <add key="UnobtrusiveJavaScriptEnabled" value="true" />
      </appSettings>'

- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '**/Limbs.Web/Limbs.Web.csproj'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PrecompileBeforePublish=true /p:UseMerge=true /p:SingleAssemblyName=AppCode /p:PackageAsSingleFile=true  /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- task: PublishBuildArtifacts@1