//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Limbs.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Limbs.Web.Resources.AccountTexts", typeof(AccountTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string _ExternalLoginsListPartial_Error {
            get {
                return ResourceManager.GetString("_ExternalLoginsListPartial_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string _ExternalLoginsListPartial_LoginButtonText {
            get {
                return ResourceManager.GetString("_ExternalLoginsListPartial_LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string _ExternalLoginsListPartial_LoginButtonTitle {
            get {
                return ResourceManager.GetString("_ExternalLoginsListPartial_LoginButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maru.
        /// </summary>
        public static string ConfirmEmail_LoginActionLink {
            get {
                return ResourceManager.GetString("ConfirmEmail_LoginActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConfirmEmail_ViewBag_Title {
            get {
                return ResourceManager.GetString("ConfirmEmail_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maru1.
        /// </summary>
        public static string DisplayEmail_TextInfo {
            get {
                return ResourceManager.GetString("DisplayEmail_TextInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maru2.
        /// </summary>
        public static string DisplayEmail_ViewBag_Title {
            get {
                return ResourceManager.GetString("DisplayEmail_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExternalLoginConfirmation_inicio_form_r_h2 {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmation_inicio_form_r_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExternalLoginConfirmation_inicio_form_r_h4 {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmation_inicio_form_r_h4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExternalLoginConfirmation_SubmitInput {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmation_SubmitInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExternalLoginConfirmation_ViewBag_Title {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmation_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExternalLoginFailure_Text_danger {
            get {
                return ResourceManager.GetString("ExternalLoginFailure_Text_danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExternalLoginFailure_ViewBag_Title {
            get {
                return ResourceManager.GetString("ExternalLoginFailure_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ForgotPassword_EmailTextBox {
            get {
                return ResourceManager.GetString("ForgotPassword_EmailTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ForgotPassword_inicio_form_r_h4 {
            get {
                return ResourceManager.GetString("ForgotPassword_inicio_form_r_h4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ForgotPassword_SubmitButton {
            get {
                return ResourceManager.GetString("ForgotPassword_SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ForgotPassword_ViewBag_Title {
            get {
                return ResourceManager.GetString("ForgotPassword_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ForgotPasswordConfirmation_inicio_form_r_h4 {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation_inicio_form_r_h4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string Login_cont_regis_post_form_ini {
            get {
                return ResourceManager.GetString("Login_cont_regis_post_form_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string Login_cont_regis_post_form_ini_link {
            get {
                return ResourceManager.GetString("Login_cont_regis_post_form_ini_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa.
        /// </summary>
        public static string Login_ForgotPasswordUrlAction {
            get {
                return ResourceManager.GetString("Login_ForgotPasswordUrlAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa.
        /// </summary>
        public static string Login_form_group_SubmitButton {
            get {
                return ResourceManager.GetString("Login_form_group_SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa.
        /// </summary>
        public static string Login_p_post_form_ini {
            get {
                return ResourceManager.GetString("Login_p_post_form_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa.
        /// </summary>
        public static string Login_ViewBag_Title {
            get {
                return ResourceManager.GetString("Login_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa.
        /// </summary>
        public static string Register_cont_regis_post_form_ini {
            get {
                return ResourceManager.GetString("Register_cont_regis_post_form_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa.
        /// </summary>
        public static string Register_cont_regis_post_form_ini_link {
            get {
                return ResourceManager.GetString("Register_cont_regis_post_form_ini_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa.
        /// </summary>
        public static string Register_inicio_form_r_h4 {
            get {
                return ResourceManager.GetString("Register_inicio_form_r_h4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ppp.
        /// </summary>
        public static string Register_post_form_ini {
            get {
                return ResourceManager.GetString("Register_post_form_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Register_ViewBag_Title {
            get {
                return ResourceManager.GetString("Register_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ResetPassword_inicio_form_r_h4 {
            get {
                return ResourceManager.GetString("ResetPassword_inicio_form_r_h4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ResetPassword_SubmitButtonValue {
            get {
                return ResourceManager.GetString("ResetPassword_SubmitButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ResetPasswordConfirmation_inicio_form_r_h4 {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation_inicio_form_r_h4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ResetPasswordConfirmation_LoginActionLink {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation_LoginActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SelectUserOrAmbassador_AmbassadorLink {
            get {
                return ResourceManager.GetString("SelectUserOrAmbassador_AmbassadorLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SelectUserOrAmbassador_UserLink {
            get {
                return ResourceManager.GetString("SelectUserOrAmbassador_UserLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SelectUserOrAmbassador_ViewBag_Title {
            get {
                return ResourceManager.GetString("SelectUserOrAmbassador_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SendCode_h4 {
            get {
                return ResourceManager.GetString("SendCode_h4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SendCode_ViewBag_Title {
            get {
                return ResourceManager.GetString("SendCode_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VerifyCode_h4 {
            get {
                return ResourceManager.GetString("VerifyCode_h4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VerifyCode_ViewBag_Title {
            get {
                return ResourceManager.GetString("VerifyCode_ViewBag_Title", resourceCulture);
            }
        }
    }
}
