//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Limbs.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AmbassadorTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AmbassadorTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Limbs.Web.Resources.AmbassadorTexts", typeof(AmbassadorTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Ésta es tu dirección?.
        /// </summary>
        public static string _Address_h3 {
            get {
                return ResourceManager.GetString("_Address_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscá en el mapa, y hacé click en la ubicación correcta.
        /// </summary>
        public static string _Address_h4 {
            get {
                return ResourceManager.GetString("_Address_h4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es importante que ubiques tu dirección correctamente para gestionar tu pedido.
        /// </summary>
        public static string _Address_h5 {
            get {
                return ResourceManager.GetString("_Address_h5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Alternativo.
        /// </summary>
        public static string Create_AlternativeEmail {
            get {
                return ResourceManager.GetString("Create_AlternativeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo nuestro contacto será vía mail, si hay otro mail que uses escribilo acá para mantenerte informado.
        /// </summary>
        public static string Create_AlternativeEmailLabel {
            get {
                return ResourceManager.GetString("Create_AlternativeEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento.
        /// </summary>
        public static string Create_Birthday {
            get {
                return ResourceManager.GetString("Create_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string Create_CreateSubmitButton {
            get {
                return ResourceManager.GetString("Create_CreateSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar datos.
        /// </summary>
        public static string Create_EditSubmitButton {
            get {
                return ResourceManager.GetString("Create_EditSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string Create_Gender {
            get {
                return ResourceManager.GetString("Create_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNI o Pasaporte.
        /// </summary>
        public static string Create_ID {
            get {
                return ResourceManager.GetString("Create_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Te estás registrando en representación de una institución u organización?.
        /// </summary>
        public static string Create_IsOrganization {
            get {
                return ResourceManager.GetString("Create_IsOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string Create_LastName {
            get {
                return ResourceManager.GetString("Create_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Create_Name {
            get {
                return ResourceManager.GetString("Create_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la organización.
        /// </summary>
        public static string Create_OrganizationName {
            get {
                return ResourceManager.GetString("Create_OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol en la organización.
        /// </summary>
        public static string Create_OrganizationRole {
            get {
                return ResourceManager.GetString("Create_OrganizationRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string Create_Phone {
            get {
                return ResourceManager.GetString("Create_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca impresora.
        /// </summary>
        public static string Create_Printer_Brand {
            get {
                return ResourceManager.GetString("Create_Printer_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿No tenés impresora?.
        /// </summary>
        public static string Create_Printer_Create_h3 {
            get {
                return ResourceManager.GetString("Create_Printer_Create_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡No hay problema! Ingresa.
        /// </summary>
        public static string Create_Printer_Create_h4_1 {
            get {
                return ResourceManager.GetString("Create_Printer_Create_h4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acá.
        /// </summary>
        public static string Create_Printer_Create_h4_2 {
            get {
                return ResourceManager.GetString("Create_Printer_Create_h4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y seguí los consejos para comprar una!.
        /// </summary>
        public static string Create_Printer_Create_h4_3 {
            get {
                return ResourceManager.GetString("Create_Printer_Create_h4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de la impresora 3D.
        /// </summary>
        public static string Create_Printer_h3 {
            get {
                return ResourceManager.GetString("Create_Printer_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alto.
        /// </summary>
        public static string Create_Printer_Height {
            get {
                return ResourceManager.GetString("Create_Printer_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Es cama caliente?.
        /// </summary>
        public static string Create_Printer_IsHotBed {
            get {
                return ResourceManager.GetString("Create_Printer_IsHotBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largo.
        /// </summary>
        public static string Create_Printer_Long {
            get {
                return ResourceManager.GetString("Create_Printer_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        public static string Create_Printer_Model {
            get {
                return ResourceManager.GetString("Create_Printer_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area de impresión.
        /// </summary>
        public static string Create_Printer_PrintingArea {
            get {
                return ResourceManager.GetString("Create_Printer_PrintingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancho.
        /// </summary>
        public static string Create_Printer_Width {
            get {
                return ResourceManager.GetString("Create_Printer_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to términos y condiciones.
        /// </summary>
        public static string Create_TermsAndConditions {
            get {
                return ResourceManager.GetString("Create_TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tus datos.
        /// </summary>
        public static string Create_Title_h2 {
            get {
                return ResourceManager.GetString("Create_Title_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay errores en el formulario, revisá los campos marcados en rojo.
        /// </summary>
        public static string Create_ValidationSummary {
            get {
                return ResourceManager.GetString("Create_ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar datos.
        /// </summary>
        public static string Create_ViewBag_Title_Edit {
            get {
                return ResourceManager.GetString("Create_ViewBag_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        public static string Create_ViewBag_Title_Register {
            get {
                return ResourceManager.GetString("Create_ViewBag_Title_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel de control.
        /// </summary>
        public static string Index_AmbassadorPanelInfo_h1 {
            get {
                return ResourceManager.GetString("Index_AmbassadorPanelInfo_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entregaste.
        /// </summary>
        public static string Index_AmbassadorPanelInfo_p1 {
            get {
                return ResourceManager.GetString("Index_AmbassadorPanelInfo_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manos.
        /// </summary>
        public static string Index_AmbassadorPanelInfo_p2 {
            get {
                return ResourceManager.GetString("Index_AmbassadorPanelInfo_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenés.
        /// </summary>
        public static string Index_AmbassadorPanelInfo_p3 {
            get {
                return ResourceManager.GetString("Index_AmbassadorPanelInfo_p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedidos.
        /// </summary>
        public static string Index_AmbassadorPanelInfo_p4 {
            get {
                return ResourceManager.GetString("Index_AmbassadorPanelInfo_p4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminadas.
        /// </summary>
        public static string Index_FinishedOrders {
            get {
                return ResourceManager.GetString("Index_FinishedOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Aún no has entregado ninguna mano!.
        /// </summary>
        public static string Index_NotFinishedOrders {
            get {
                return ResourceManager.GetString("Index_NotFinishedOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tienes nuevos pedidos asignados.
        /// </summary>
        public static string Index_NotPendigOrders {
            get {
                return ResourceManager.GetString("Index_NotPendigOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tus pedidos.
        /// </summary>
        public static string Index_PendingOrders {
            get {
                return ResourceManager.GetString("Index_PendingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedidos entrantes.
        /// </summary>
        public static string Index_PendingToAssignOrders {
            get {
                return ResourceManager.GetString("Index_PendingToAssignOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel de Embajador.
        /// </summary>
        public static string Index_ViewBag_Title {
            get {
                return ResourceManager.GetString("Index_ViewBag_Title", resourceCulture);
            }
        }
    }
}
