//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Limbs.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelpTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Limbs.Web.Resources.HelpTexts", typeof(HelpTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda.
        /// </summary>
        public static string Index_h2 {
            get {
                return ResourceManager.GetString("Index_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Hola!.
        /// </summary>
        public static string Pedir_h2 {
            get {
                return ResourceManager.GetString("Pedir_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nos alegra que quieras una prótesis, vamos a guiarte paso a paso..
        /// </summary>
        public static string Pedir_p1 {
            get {
                return ResourceManager.GetString("Pedir_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para poder realizar el pedido, tenés tener una cuenta en Limbs..
        /// </summary>
        public static string Pedir_p2 {
            get {
                return ResourceManager.GetString("Pedir_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Tenés una cuenta?.
        /// </summary>
        public static string Pedir_Pregunta {
            get {
                return ResourceManager.GetString("Pedir_Pregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Si! Ya tengo una cuenta.
        /// </summary>
        public static string Pedir_UrlActionLogin {
            get {
                return ResourceManager.GetString("Pedir_UrlActionLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, no tengo una cuenta.
        /// </summary>
        public static string Pedir_UrlActionRegister {
            get {
                return ResourceManager.GetString("Pedir_UrlActionRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedir una prótesis.
        /// </summary>
        public static string Pedir_ViewBag_Title {
            get {
                return ResourceManager.GetString("Pedir_ViewBag_Title", resourceCulture);
            }
        }
    }
}
