//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Limbs.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Limbs.Web.Resources.HomeTexts", typeof(HomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Tenés una impresora 3D y querés ayudar? ¡Inscribite!.
        /// </summary>
        public static string Index_body_embajadores_p1 {
            get {
                return ResourceManager.GetString("Index_body_embajadores_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un &quot;Embajador Atómico&quot; puede ser cualquier persona mayor de 18 años con una impresora 3D y que quiera ayudar (desde cualquier parte del mundo). Nosotros enviamos los planos, instrucciones y el costo de los materiales (si así lo solicita)..
        /// </summary>
        public static string Index_body_embajadores_p2 {
            get {
                return ResourceManager.GetString("Index_body_embajadores_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limbs es una plataforma que te ayudará en 3 simples pasos a tener tu mano, brazo o cualquier otra parte impresa en 3D..
        /// </summary>
        public static string Index_center_text {
            get {
                return ResourceManager.GetString("Index_center_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las manos mecánicas están impresas con PLA, un derivado del maíz que no generará picazón.
        /// </summary>
        public static string Index_cont_pedir_texto_inicio_center1 {
            get {
                return ResourceManager.GetString("Index_cont_pedir_texto_inicio_center1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los diseños son open source, podés bajarlos gratis desde:.
        /// </summary>
        public static string Index_cont_pedir_texto_inicio_center2 {
            get {
                return ResourceManager.GetString("Index_cont_pedir_texto_inicio_center2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Cómo está compuesta?.
        /// </summary>
        public static string Index_cont_pedir_texto_inicio_h1 {
            get {
                return ResourceManager.GetString("Index_cont_pedir_texto_inicio_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRES SIMPLES PASOS.
        /// </summary>
        public static string Index_imagen_pedir_h1 {
            get {
                return ResourceManager.GetString("Index_imagen_pedir_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manotón.
        /// </summary>
        public static string Index_manoton_h1 {
            get {
                return ResourceManager.GetString("Index_manoton_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saber más.
        /// </summary>
        public static string Index_manoton_link {
            get {
                return ResourceManager.GetString("Index_manoton_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El #MANOTÓN es un evento en el que se convocan chicos que hayan solicitado un prótesis mediante la plataforma LIMBS. Durante el día se ensamblan y entregan las manos mecánicas, ¡Convirtiendo chicos en super héroes!.
        /// </summary>
        public static string Index_manoton_p {
            get {
                return ResourceManager.GetString("Index_manoton_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Más Información.
        /// </summary>
        public static string Index_MoreInformation {
            get {
                return ResourceManager.GetString("Index_MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ser embajador.
        /// </summary>
        public static string Index_RegisterUrlAction {
            get {
                return ResourceManager.GetString("Index_RegisterUrlAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMBAJADORES.
        /// </summary>
        public static string Index_texto_embajadores_h1_1 {
            get {
                return ResourceManager.GetString("Index_texto_embajadores_h1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATÓMICOS.
        /// </summary>
        public static string Index_texto_embajadores_h1_2 {
            get {
                return ResourceManager.GetString("Index_texto_embajadores_h1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Bienvenido a Limbs!.
        /// </summary>
        public static string Index_texto_inicio_h1 {
            get {
                return ResourceManager.GetString("Index_texto_inicio_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde Limbs -un proyecto de Atomic Lab- queremos que todas las personas que lo necesiten tengan su prótesis impresa en 3D, sin que el dinero sea una barrera. Por eso,.
        /// </summary>
        public static string Index_texto_inicio_p1 {
            get {
                return ResourceManager.GetString("Index_texto_inicio_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to las entregamos de manera GRATUITA..
        /// </summary>
        public static string Index_texto_inicio_p2 {
            get {
                return ResourceManager.GetString("Index_texto_inicio_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        public static string Index_UrlAction_Login {
            get {
                return ResourceManager.GetString("Index_UrlAction_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedir una prótesis.
        /// </summary>
        public static string Index_UrlAction_Pedir {
            get {
                return ResourceManager.GetString("Index_UrlAction_Pedir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrate.
        /// </summary>
        public static string Index_UrlAction_Register {
            get {
                return ResourceManager.GetString("Index_UrlAction_Register", resourceCulture);
            }
        }
    }
}
