//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Limbs.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ManageTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManageTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Limbs.Web.Resources.ManageTexts", typeof(ManageTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string _UserInfo_Address {
            get {
                return ResourceManager.GetString("_UserInfo_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacimiento.
        /// </summary>
        public static string _UserInfo_Birth {
            get {
                return ResourceManager.GetString("_UserInfo_Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string _UserInfo_City {
            get {
                return ResourceManager.GetString("_UserInfo_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string _UserInfo_Country {
            get {
                return ResourceManager.GetString("_UserInfo_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string _UserInfo_Email {
            get {
                return ResourceManager.GetString("_UserInfo_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string _UserInfo_LastName {
            get {
                return ResourceManager.GetString("_UserInfo_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string _UserInfo_Name {
            get {
                return ResourceManager.GetString("_UserInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string _UserInfo_Phone {
            get {
                return ResourceManager.GetString("_UserInfo_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar contraseña.
        /// </summary>
        public static string Actions_ChangePasswordUrlAction {
            get {
                return ResourceManager.GetString("Actions_ChangePasswordUrlAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar datos.
        /// </summary>
        public static string Actions_EditUrlAction {
            get {
                return ResourceManager.GetString("Actions_EditUrlAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensajes .
        /// </summary>
        public static string Actions_MessagesUrlAction {
            get {
                return ResourceManager.GetString("Actions_MessagesUrlAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear contraseña.
        /// </summary>
        public static string Actions_SetPasswordUrlAction {
            get {
                return ResourceManager.GetString("Actions_SetPasswordUrlAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciaste sesión con Facebook, podes crear una contraseña.
        /// </summary>
        public static string Actions_SetPasswordUrlAction_span {
            get {
                return ResourceManager.GetString("Actions_SetPasswordUrlAction_span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar número de teléfono.
        /// </summary>
        public static string AddPhoneNumber_h4 {
            get {
                return ResourceManager.GetString("AddPhoneNumber_h4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Teléfono.
        /// </summary>
        public static string AddPhoneNumber_ViewBag_Title {
            get {
                return ResourceManager.GetString("AddPhoneNumber_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar contraseña.
        /// </summary>
        public static string ChangePassword_ViewBag_Title {
            get {
                return ResourceManager.GetString("ChangePassword_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrar.
        /// </summary>
        public static string Index__ViewBag_Title {
            get {
                return ResourceManager.GetString("Index__ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis datos.
        /// </summary>
        public static string Index_head_info_h1 {
            get {
                return ResourceManager.GetString("Index_head_info_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Index_head_info_p {
            get {
                return ResourceManager.GetString("Index_head_info_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia sesión con tu cuenta de.
        /// </summary>
        public static string ManageLogins_LoginSubmitInput_title {
            get {
                return ResourceManager.GetString("ManageLogins_LoginSubmitInput_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicios de sesión registrados.
        /// </summary>
        public static string ManageLogins_RegisteredLogins {
            get {
                return ResourceManager.GetString("ManageLogins_RegisteredLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar inicio de sesión con tu cuenta de.
        /// </summary>
        public static string ManageLogins_RemoveSubmitInput_title {
            get {
                return ResourceManager.GetString("ManageLogins_RemoveSubmitInput_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string ManageLogins_RemoveSubmitInput_value {
            get {
                return ResourceManager.GetString("ManageLogins_RemoveSubmitInput_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestiona tus inicios de sesión externos.
        /// </summary>
        public static string ManageLogins_ViewBag_Title {
            get {
                return ResourceManager.GetString("ManageLogins_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciaste sesion con Facebook, creá una cuenta con tu propia contraseña.
        /// </summary>
        public static string SetPassword_inicio_form_r_h4 {
            get {
                return ResourceManager.GetString("SetPassword_inicio_form_r_h4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string SetPassword_SubmitInput_value {
            get {
                return ResourceManager.GetString("SetPassword_SubmitInput_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear contraseña.
        /// </summary>
        public static string SetPassword_ViewBag_Title {
            get {
                return ResourceManager.GetString("SetPassword_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese número de verificación.
        /// </summary>
        public static string VerifyPhoneNumber_h4 {
            get {
                return ResourceManager.GetString("VerifyPhoneNumber_h4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string VerifyPhoneNumber_SubmitInput_value {
            get {
                return ResourceManager.GetString("VerifyPhoneNumber_SubmitInput_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificar número de teléfono.
        /// </summary>
        public static string VerifyPhoneNumber_ViewBag_Title {
            get {
                return ResourceManager.GetString("VerifyPhoneNumber_ViewBag_Title", resourceCulture);
            }
        }
    }
}
