//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Limbs.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Limbs.Web.Resources.MessagesTexts", typeof(MessagesTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string _InboxPartial_ActionLinkDelete {
            get {
                return ResourceManager.GetString("_InboxPartial_ActionLinkDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tenés mensajes.
        /// </summary>
        public static string _InboxPartial_anyMessages {
            get {
                return ResourceManager.GetString("_InboxPartial_anyMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string _Reply_SubmitButtonValue {
            get {
                return ResourceManager.GetString("_Reply_SubmitButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir al pedido.
        /// </summary>
        public static string Create_DetailsUrlAction {
            get {
                return ResourceManager.GetString("Create_DetailsUrlAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string Create_SubmitButtonValue {
            get {
                return ResourceManager.GetString("Create_SubmitButtonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensajes.
        /// </summary>
        public static string Create_ViewBag_Title {
            get {
                return ResourceManager.GetString("Create_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro querés borrar el mensaje?.
        /// </summary>
        public static string Delete_h3 {
            get {
                return ResourceManager.GetString("Delete_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string Delete_SubmitButton {
            get {
                return ResourceManager.GetString("Delete_SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir al pedido.
        /// </summary>
        public static string Details_DetailsUrlAction {
            get {
                return ResourceManager.GetString("Details_DetailsUrlAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando mensajes.
        /// </summary>
        public static string Details_Loading {
            get {
                return ResourceManager.GetString("Details_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenés más mensajes sin leer.
        /// </summary>
        public static string Details_More_Messages {
            get {
                return ResourceManager.GetString("Details_More_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensajes.
        /// </summary>
        public static string Details_ViewBag_Title {
            get {
                return ResourceManager.GetString("Details_ViewBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        public static string Edit_IndexActionLink {
            get {
                return ResourceManager.GetString("Edit_IndexActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Edit_SubmitInput {
            get {
                return ResourceManager.GetString("Edit_SubmitInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar los mensajes. Pruebe refrescando la página.
        /// </summary>
        public static string Inbox_error1 {
            get {
                return ResourceManager.GetString("Inbox_error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al actualizar los mensajes. Si el error continua, refresque la página.
        /// </summary>
        public static string Inbox_error2 {
            get {
                return ResourceManager.GetString("Inbox_error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando mensajes.
        /// </summary>
        public static string Inbox_inbox_status {
            get {
                return ResourceManager.GetString("Inbox_inbox_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensajes.
        /// </summary>
        public static string Inbox_ViewBag_Title {
            get {
                return ResourceManager.GetString("Inbox_ViewBag_Title", resourceCulture);
            }
        }
    }
}
