//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Limbs.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelsTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelsTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Limbs.Web.Resources.ModelsTexts", typeof(ModelsTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amputación.
        /// </summary>
        public static string AmputationTypeDetails_Name {
            get {
                return ResourceManager.GetString("AmputationTypeDetails_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (si es posible).
        /// </summary>
        public static string ColorDetails_Name_Description {
            get {
                return ResourceManager.GetString("ColorDetails_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string ColorDetails_Name_Name {
            get {
                return ResourceManager.GetString("ColorDetails_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amputación.
        /// </summary>
        public static string NewOrder_AmputationTypeFkId {
            get {
                return ResourceManager.GetString("NewOrder_AmputationTypeFkId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios.
        /// </summary>
        public static string OrderDetails_Comments {
            get {
                return ResourceManager.GetString("OrderDetails_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courier.
        /// </summary>
        public static string OrderDetails_DeliveryCourier {
            get {
                return ResourceManager.GetString("OrderDetails_DeliveryCourier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiqueta postal.
        /// </summary>
        public static string OrderDetails_DeliveryPostalLabel {
            get {
                return ResourceManager.GetString("OrderDetails_DeliveryPostalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string OrderDetails_DeliveryTrackingCode {
            get {
                return ResourceManager.GetString("OrderDetails_DeliveryTrackingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido #.
        /// </summary>
        public static string OrderDetails_Id {
            get {
                return ResourceManager.GetString("OrderDetails_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historial de cambios.
        /// </summary>
        public static string OrderDetails_Log {
            get {
                return ResourceManager.GetString("OrderDetails_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Cuál?.
        /// </summary>
        public static string OrderDetails_ProductType {
            get {
                return ResourceManager.GetString("OrderDetails_ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prueba de entrega.
        /// </summary>
        public static string OrderDetails_ProofOfDelivery {
            get {
                return ResourceManager.GetString("OrderDetails_ProofOfDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaños.
        /// </summary>
        public static string OrderDetails_Sizes {
            get {
                return ResourceManager.GetString("OrderDetails_Sizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string OrderDetails_Status {
            get {
                return ResourceManager.GetString("OrderDetails_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string OrderRequesterDetails_City {
            get {
                return ResourceManager.GetString("OrderRequesterDetails_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string OrderRequesterDetails_Country {
            get {
                return ResourceManager.GetString("OrderRequesterDetails_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string OrderRequesterDetails_Phone {
            get {
                return ResourceManager.GetString("OrderRequesterDetails_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido del usuario.
        /// </summary>
        public static string OrderRequesterDetails_UserLastName {
            get {
                return ResourceManager.GetString("OrderRequesterDetails_UserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del usuario.
        /// </summary>
        public static string OrderRequesterDetails_UserName {
            get {
                return ResourceManager.GetString("OrderRequesterDetails_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amputación.
        /// </summary>
        public static string OrderUpdate_AmputationTypeFkId {
            get {
                return ResourceManager.GetString("OrderUpdate_AmputationTypeFkId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (si es posible).
        /// </summary>
        public static string OrderUpdate_ColorFkId_Description {
            get {
                return ResourceManager.GetString("OrderUpdate_ColorFkId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string OrderUpdate_ColorFkId_Name {
            get {
                return ResourceManager.GetString("OrderUpdate_ColorFkId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios.
        /// </summary>
        public static string OrderUpdate_Comments {
            get {
                return ResourceManager.GetString("OrderUpdate_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Cuál?.
        /// </summary>
        public static string OrderUpdate_ProductType {
            get {
                return ResourceManager.GetString("OrderUpdate_ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo requerido.
        /// </summary>
        public static string RequiredErrorMessage {
            get {
                return ResourceManager.GetString("RequiredErrorMessage", resourceCulture);
            }
        }
    }
}
