//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Limbs.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrdersTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrdersTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Limbs.Web.Resources.OrdersTexts", typeof(OrdersTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivos generados!.
        /// </summary>
        public static string _Action_generated {
            get {
                return ResourceManager.GetString("_Action_generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar pedido.
        /// </summary>
        public static string _Actions_AcceptOrder {
            get {
                return ResourceManager.GetString("_Actions_AcceptOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar pedido.
        /// </summary>
        public static string _Actions_AcceptReject {
            get {
                return ResourceManager.GetString("_Actions_AcceptReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar envío.
        /// </summary>
        public static string _Actions_ArrangeDelivery {
            get {
                return ResourceManager.GetString("_Actions_ArrangeDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar embajador.
        /// </summary>
        public static string _Actions_AssignAmbassadorAuto {
            get {
                return ResourceManager.GetString("_Actions_AssignAmbassadorAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informar datos incorrectos.
        /// </summary>
        public static string _Actions_bn_delete {
            get {
                return ResourceManager.GetString("_Actions_bn_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios.
        /// </summary>
        public static string _Actions_Comments {
            get {
                return ResourceManager.GetString("_Actions_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generando archivos.
        /// </summary>
        public static string _Actions_generating {
            get {
                return ResourceManager.GetString("_Actions_generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        public static string _Actions_Home {
            get {
                return ResourceManager.GetString("_Actions_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya entregué el pedido.
        /// </summary>
        public static string _Actions_OrderDelivered {
            get {
                return ResourceManager.GetString("_Actions_OrderDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminé de imprimir.
        /// </summary>
        public static string _Actions_OrderFinished {
            get {
                return ResourceManager.GetString("_Actions_OrderFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informar datos incorrectos.
        /// </summary>
        public static string _Actions_ReportWrongInfo {
            get {
                return ResourceManager.GetString("_Actions_ReportWrongInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informar.
        /// </summary>
        public static string _Actions_SubmitButton {
            get {
                return ResourceManager.GetString("_Actions_SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar pedido.
        /// </summary>
        public static string _Actions_UrlActionEditOrder {
            get {
                return ResourceManager.GetString("_Actions_UrlActionEditOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medir mano.
        /// </summary>
        public static string _Actions_UrlActionManoMedidas {
            get {
                return ResourceManager.GetString("_Actions_UrlActionManoMedidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar mensaje.
        /// </summary>
        public static string _Actions_UrlActionMessages {
            get {
                return ResourceManager.GetString("_Actions_UrlActionMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generar archivos.
        /// </summary>
        public static string _Actions_UrlActionProductGenerate {
            get {
                return ResourceManager.GetString("_Actions_UrlActionProductGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagenes incorrectas.
        /// </summary>
        public static string _Actions_WrongImages {
            get {
                return ResourceManager.GetString("_Actions_WrongImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar envío.
        /// </summary>
        public static string _DeliveryInfo_ArrangeDelivery {
            get {
                return ResourceManager.GetString("_DeliveryInfo_ArrangeDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No disponible.
        /// </summary>
        public static string _DeliveryInfo_DeliveryTrackingCodeNotAvailable {
            get {
                return ResourceManager.GetString("_DeliveryInfo_DeliveryTrackingCodeNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar.
        /// </summary>
        public static string _DeliveryInfo_Download {
            get {
                return ResourceManager.GetString("_DeliveryInfo_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de entrega.
        /// </summary>
        public static string _DeliveryInfo_OrderType {
            get {
                return ResourceManager.GetString("_DeliveryInfo_OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generando archivos.
        /// </summary>
        public static string _Header_Generating_h2 {
            get {
                return ResourceManager.GetString("_Header_Generating_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguarde, esta operación puede durar hasta 2 minutos.
        /// </summary>
        public static string _Header_Generating_p1 {
            get {
                return ResourceManager.GetString("_Header_Generating_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No refresque la página.
        /// </summary>
        public static string _Header_Generating_p2 {
            get {
                return ResourceManager.GetString("_Header_Generating_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido.
        /// </summary>
        public static string _Header_h1 {
            get {
                return ResourceManager.GetString("_Header_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string _Header_state {
            get {
                return ResourceManager.GetString("_Header_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cargar los mensajes.
        /// </summary>
        public static string _Messages_errorLoading_p1 {
            get {
                return ResourceManager.GetString("_Messages_errorLoading_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para ver los mensajes, vaya a su.
        /// </summary>
        public static string _Messages_errorLoading_p2 {
            get {
                return ResourceManager.GetString("_Messages_errorLoading_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bandeja de entrada.
        /// </summary>
        public static string _Messages_errorLoading_p3 {
            get {
                return ResourceManager.GetString("_Messages_errorLoading_p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensajes.
        /// </summary>
        public static string _Messages_h3 {
            get {
                return ResourceManager.GetString("_Messages_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando mensajes.
        /// </summary>
        public static string _Messages_loading {
            get {
                return ResourceManager.GetString("_Messages_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del pedido.
        /// </summary>
        public static string _OrderInfo_h3 {
            get {
                return ResourceManager.GetString("_OrderInfo_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotos.
        /// </summary>
        public static string _OrderInfo_photos {
            get {
                return ResourceManager.GetString("_OrderInfo_photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No medido.
        /// </summary>
        public static string _OrderInfo_sizeNull {
            get {
                return ResourceManager.GetString("_OrderInfo_sizeNull", resourceCulture);
            }
        }
    }
}
