//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Limbs.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Limbs.Web.Resources.SharedTexts", typeof(SharedTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        public static string _LoginPartial_cerrar_sesion {
            get {
                return ResourceManager.GetString("_LoginPartial_cerrar_sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string _LoginPartial_LoginUrlAction {
            get {
                return ResourceManager.GetString("_LoginPartial_LoginUrlAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string _LoginPartial_RegisterUrlAction {
            get {
                return ResourceManager.GetString("_LoginPartial_RegisterUrlAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información del error.
        /// </summary>
        public static string Error_errorInfo {
            get {
                return ResourceManager.GetString("Error_errorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Más información.
        /// </summary>
        public static string Error_moreInfo {
            get {
                return ResourceManager.GetString("Error_moreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error. No te preocupes, ya nos enteramos y vamos a solucionarlo lo antes posible.
        /// </summary>
        public static string Error_text_danger_h2 {
            get {
                return ResourceManager.GetString("Error_text_danger_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string Error_User {
            get {
                return ResourceManager.GetString("Error_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_ViegBag_Title {
            get {
                return ResourceManager.GetString("Error_ViegBag_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atomic Lab es una iniciativa que busca inventar las mejores soluciones para ayudar a las personas.
        /// </summary>
        public static string Footer_footer_company_about {
            get {
                return ResourceManager.GetString("Footer_footer_company_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acá.
        /// </summary>
        public static string Footer_ReportError_Link {
            get {
                return ResourceManager.GetString("Footer_ReportError_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Encontraste errores o mejoras en esta plataforma? - Hacé click.
        /// </summary>
        public static string Footer_ReportError1 {
            get {
                return ResourceManager.GetString("Footer_ReportError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y ayudanos a mejorarla.
        /// </summary>
        public static string Footer_ReportError2 {
            get {
                return ResourceManager.GetString("Footer_ReportError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estamos en todas las redes sociales. No te olvides de compartir con tus amigos lo que hacemos, así más personas pueden solicitarnos su mano.
        /// </summary>
        public static string Footer_SocialMedia_p {
            get {
                return ResourceManager.GetString("Footer_SocialMedia_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactanos por las redes.
        /// </summary>
        public static string Footer_SocialMedia_span {
            get {
                return ResourceManager.GetString("Footer_SocialMedia_span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunidad de Embajadores.
        /// </summary>
        public static string Header_Comunidad {
            get {
                return ResourceManager.GetString("Header_Comunidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donar.
        /// </summary>
        public static string Header_Donar {
            get {
                return ResourceManager.GetString("Header_Donar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Header_home {
            get {
                return ResourceManager.GetString("Header_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string Header_LoginUrlAction {
            get {
                return ResourceManager.GetString("Header_LoginUrlAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Header_Manual {
            get {
                return ResourceManager.GetString("Header_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedir una prótesis.
        /// </summary>
        public static string Header_PedirUrlAction {
            get {
                return ResourceManager.GetString("Header_PedirUrlAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string Header_RegisterUrlAction {
            get {
                return ResourceManager.GetString("Header_RegisterUrlAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta cuenta ha sido bloqueada, por favor inténtelo de nuevo más tarde.
        /// </summary>
        public static string Lockout_h2 {
            get {
                return ResourceManager.GetString("Lockout_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueodo.
        /// </summary>
        public static string Lockout_ViewBag_Title {
            get {
                return ResourceManager.GetString("Lockout_ViewBag_Title", resourceCulture);
            }
        }
    }
}
