//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Limbs.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UsersTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsersTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Limbs.Web.Resources.UsersTexts", typeof(UsersTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Ésta es tu dirección?.
        /// </summary>
        public static string _Address_h3 {
            get {
                return ResourceManager.GetString("_Address_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscá en el mapa, y hacé click en la ubicación correcta.
        /// </summary>
        public static string _Address_h4 {
            get {
                return ResourceManager.GetString("_Address_h4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es importante que ubiques tu dirección correctamente para gestionar tu pedido.
        /// </summary>
        public static string _Address_h5 {
            get {
                return ResourceManager.GetString("_Address_h5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Alternativo.
        /// </summary>
        public static string Create_AlternativeEmail {
            get {
                return ResourceManager.GetString("Create_AlternativeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo nuestro contacto será vía mail, si hay otro mail que uses escribilo acá para mantenerte informado.
        /// </summary>
        public static string Create_AlternativeEmail_Label {
            get {
                return ResourceManager.GetString("Create_AlternativeEmail_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string Create_drop_op1 {
            get {
                return ResourceManager.GetString("Create_drop_op1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SI.
        /// </summary>
        public static string Create_drop_op2 {
            get {
                return ResourceManager.GetString("Create_drop_op2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tus datos.
        /// </summary>
        public static string Create_h2_1 {
            get {
                return ResourceManager.GetString("Create_h2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del usuario de la mano.
        /// </summary>
        public static string Create_h2_2 {
            get {
                return ResourceManager.GetString("Create_h2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Sos el usuario de la mano?.
        /// </summary>
        public static string Create_h3 {
            get {
                return ResourceManager.GetString("Create_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Declara que es mayor de 18 años?.
        /// </summary>
        public static string Create_isAdultCheck {
            get {
                return ResourceManager.GetString("Create_isAdultCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar datos.
        /// </summary>
        public static string Create_RegisterButton_Edit {
            get {
                return ResourceManager.GetString("Create_RegisterButton_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string Create_RegisterButton_Register {
            get {
                return ResourceManager.GetString("Create_RegisterButton_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Documento de Identidad / Pasaporte.
        /// </summary>
        public static string Create_ResponsableDni {
            get {
                return ResourceManager.GetString("Create_ResponsableDni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar el número completo. Según el país, puede ser también conocido como: Cédula de Identidad (CI), Cédula de Ciudadanía (CC), Tarjeta de Identidad (TI), Registro Civil (RC), Cédula de Extranjería (CE), Carné de Identidad (CI), Documento Nacional de Identidad (DNI), Documento Único de Identidad (DUI), identificación oficial o identificación (ID), Clave Única de Registro de Población (CURP), etc.
        /// </summary>
        public static string Create_ResponsableDni_Label {
            get {
                return ResourceManager.GetString("Create_ResponsableDni_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string Create_ResponsableLastName {
            get {
                return ResourceManager.GetString("Create_ResponsableLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Create_ResponsableName {
            get {
                return ResourceManager.GetString("Create_ResponsableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acepto los.
        /// </summary>
        public static string Create_termsAndConditions {
            get {
                return ResourceManager.GetString("Create_termsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to términos y condiciones.
        /// </summary>
        public static string Create_TermsAndConditionsActionLink {
            get {
                return ResourceManager.GetString("Create_TermsAndConditionsActionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento.
        /// </summary>
        public static string Create_UserBirth {
            get {
                return ResourceManager.GetString("Create_UserBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNI o Pasaporte.
        /// </summary>
        public static string Create_UserDni {
            get {
                return ResourceManager.GetString("Create_UserDni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string Create_UserGender {
            get {
                return ResourceManager.GetString("Create_UserGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string Create_UserLastName {
            get {
                return ResourceManager.GetString("Create_UserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Create_UserName {
            get {
                return ResourceManager.GetString("Create_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string Create_UserPhone {
            get {
                return ResourceManager.GetString("Create_UserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay errores en el formulario, revisá los campos marcados en rojo.
        /// </summary>
        public static string Create_ValidationSummary {
            get {
                return ResourceManager.GetString("Create_ValidationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar datos.
        /// </summary>
        public static string Create_ViewBag_Title_Edit {
            get {
                return ResourceManager.GetString("Create_ViewBag_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro.
        /// </summary>
        public static string Create_ViewBag_Title_Register {
            get {
                return ResourceManager.GetString("Create_ViewBag_Title_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creado.
        /// </summary>
        public static string Index_headerOrder_Created {
            get {
                return ResourceManager.GetString("Index_headerOrder_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido N°.
        /// </summary>
        public static string Index_headerOrder_Number {
            get {
                return ResourceManager.GetString("Index_headerOrder_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedir una prótesis.
        /// </summary>
        public static string Index_ManoPedirUrlAction {
            get {
                return ResourceManager.GetString("Index_ManoPedirUrlAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Aún no has pedido ninguna prótesis!.
        /// </summary>
        public static string Index_NotOrders {
            get {
                return ResourceManager.GetString("Index_NotOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podrás pedir la prótesis recién cuando el usuario cumpla 4 años de edad.
        /// </summary>
        public static string Index_NotValidAge_h2 {
            get {
                return ResourceManager.GetString("Index_NotValidAge_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestra experiencia luego de varios años diseñando, imprimiendo y probando prótesis mecánicas 3D, nos dejan en claro que las mismas no se recomiendan bajo ningún concepto para que sean utilizadas por menores de 4 años.
        ///Por diferentes motivos, las personas no tienen el desarrollo mínimo para usar y ser conscientes de la prótesis mecánica, la misma requiere de un aprendizaje que no es posible lograr a esa edad, y genera más frustraciones que alegrías..
        /// </summary>
        public static string Index_NotValidAge_p {
            get {
                return ResourceManager.GetString("Index_NotValidAge_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tus pedidos.
        /// </summary>
        public static string Index_Orders_h3 {
            get {
                return ResourceManager.GetString("Index_Orders_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Tu prótesis está en camino!.
        /// </summary>
        public static string Index_OrderStatus_ArrangeDelivery_h3 {
            get {
                return ResourceManager.GetString("Index_OrderStatus_ArrangeDelivery_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisá los detalles de la entrega aquí.
        /// </summary>
        public static string Index_OrderStatus_ArrangeDelivery_p {
            get {
                return ResourceManager.GetString("Index_OrderStatus_ArrangeDelivery_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu prótesis ya fue entregada.
        /// </summary>
        public static string Index_OrderStatus_Delivered_h3 {
            get {
                return ResourceManager.GetString("Index_OrderStatus_Delivered_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu pedido fue realizado con éxito.
        /// </summary>
        public static string Index_OrderStatus_NotAssigned_h3 {
            get {
                return ResourceManager.GetString("Index_OrderStatus_NotAssigned_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronto asignaremos tu caso a un embajador.
        /// </summary>
        public static string Index_OrderStatus_NotAssigned_p {
            get {
                return ResourceManager.GetString("Index_OrderStatus_NotAssigned_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Tu prótesis se esta imprimiendo!.
        /// </summary>
        public static string Index_OrderStatus_Pending_h3 {
            get {
                return ResourceManager.GetString("Index_OrderStatus_Pending_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuando esté terminada te contactaremos.
        /// </summary>
        public static string Index_OrderStatus_Pending_p {
            get {
                return ResourceManager.GetString("Index_OrderStatus_Pending_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu pedido fue asignado a un embajador Atómico.
        /// </summary>
        public static string Index_OrderStatus_PreAssigned_h3 {
            get {
                return ResourceManager.GetString("Index_OrderStatus_PreAssigned_h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Pronto comenzará a imprimirse tu prótesis!.
        /// </summary>
        public static string Index_OrderStatus_PreAssigned_p {
            get {
                return ResourceManager.GetString("Index_OrderStatus_PreAssigned_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel usuario.
        /// </summary>
        public static string Index_ViewBag_Title {
            get {
                return ResourceManager.GetString("Index_ViewBag_Title", resourceCulture);
            }
        }
    }
}
