// <auto-generated />
namespace Limbs.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cretetableCOVIDEmbajadorEntregable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cretetableCOVIDEmbajadorEntregable));
        
        string IMigrationMetadata.Id
        {
            get { return "202003251126543_crete-table-COVIDEmbajadorEntregable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
