//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Limbs.Web.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Limbs.Web.Entities.Resources.ModelTexts", typeof(ModelTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección (solo calle y altura).
        /// </summary>
        public static string Ambassador_Address {
            get {
                return ResourceManager.GetString("Ambassador_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección (otros datos).
        /// </summary>
        public static string Ambassador_Address2 {
            get {
                return ResourceManager.GetString("Ambassador_Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Alternativo.
        /// </summary>
        public static string Ambassador_AlternativeEmail {
            get {
                return ResourceManager.GetString("Ambassador_AlternativeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string Ambassador_AmbassadorLastName {
            get {
                return ResourceManager.GetString("Ambassador_AmbassadorLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Ambassador_AmbassadorName {
            get {
                return ResourceManager.GetString("Ambassador_AmbassadorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha inválida.
        /// </summary>
        public static string Ambassador_Birth_ErrorMessage {
            get {
                return ResourceManager.GetString("Ambassador_Birth_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento.
        /// </summary>
        public static string Ambassador_Birth_Name {
            get {
                return ResourceManager.GetString("Ambassador_Birth_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string Ambassador_City {
            get {
                return ResourceManager.GetString("Ambassador_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Ambassador_Country {
            get {
                return ResourceManager.GetString("Ambassador_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento de identidad o pasaporte.
        /// </summary>
        public static string Ambassador_Dni {
            get {
                return ResourceManager.GetString("Ambassador_Dni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, por cuenta propia.
        /// </summary>
        public static string Ambassador_enum_Organization_1 {
            get {
                return ResourceManager.GetString("Ambassador_enum_Organization_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escuela.
        /// </summary>
        public static string Ambassador_enum_Organization_2 {
            get {
                return ResourceManager.GetString("Ambassador_enum_Organization_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universidad.
        /// </summary>
        public static string Ambassador_enum_Organization_3 {
            get {
                return ResourceManager.GetString("Ambassador_enum_Organization_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organismo Gubernamental.
        /// </summary>
        public static string Ambassador_enum_Organization_4 {
            get {
                return ResourceManager.GetString("Ambassador_enum_Organization_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organización SIN fines de lucro.
        /// </summary>
        public static string Ambassador_enum_Organization_5 {
            get {
                return ResourceManager.GetString("Ambassador_enum_Organization_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organización CON fines de lucro.
        /// </summary>
        public static string Ambassador_enum_Organization_6 {
            get {
                return ResourceManager.GetString("Ambassador_enum_Organization_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Género.
        /// </summary>
        public static string Ambassador_Gender {
            get {
                return ResourceManager.GetString("Ambassador_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organización.
        /// </summary>
        public static string Ambassador_Organization {
            get {
                return ResourceManager.GetString("Ambassador_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la organización.
        /// </summary>
        public static string Ambassador_OrganizationName {
            get {
                return ResourceManager.GetString("Ambassador_OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string Ambassador_Phone {
            get {
                return ResourceManager.GetString("Ambassador_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol en la organización.
        /// </summary>
        public static string Ambassador_RoleInOrganization {
            get {
                return ResourceManager.GetString("Ambassador_RoleInOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string Ambassador_State {
            get {
                return ResourceManager.GetString("Ambassador_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo requerido.
        /// </summary>
        public static string RequiredErrorMessage {
            get {
                return ResourceManager.GetString("RequiredErrorMessage", resourceCulture);
            }
        }
    }
}
