//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Limbs.Web.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Limbs.Web.Entities.Resources.ModelTexts", typeof(ModelTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Account_Code {
            get {
                return ResourceManager.GetString("Account_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma la nueva contraseña.
        /// </summary>
        public static string Account_ConfirmPassword {
            get {
                return ResourceManager.GetString("Account_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña no coincide.
        /// </summary>
        public static string Account_ConfirmPassword_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_ConfirmPassword_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Account_Email {
            get {
                return ResourceManager.GetString("Account_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Account_Password {
            get {
                return ResourceManager.GetString("Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe tener por lo menos 6 caracteres.
        /// </summary>
        public static string Account_Password_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_Password_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Recordar este navegador?.
        /// </summary>
        public static string Account_RememberBrowser {
            get {
                return ResourceManager.GetString("Account_RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Recordarme?.
        /// </summary>
        public static string Account_RememberMe {
            get {
                return ResourceManager.GetString("Account_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección (solo calle y altura).
        /// </summary>
        public static string Ambassador_Address {
            get {
                return ResourceManager.GetString("Ambassador_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección (otros datos).
        /// </summary>
        public static string Ambassador_Address2 {
            get {
                return ResourceManager.GetString("Ambassador_Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Alternativo.
        /// </summary>
        public static string Ambassador_AlternativeEmail {
            get {
                return ResourceManager.GetString("Ambassador_AlternativeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string Ambassador_AmbassadorLastName {
            get {
                return ResourceManager.GetString("Ambassador_AmbassadorLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Ambassador_AmbassadorName {
            get {
                return ResourceManager.GetString("Ambassador_AmbassadorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha inválida.
        /// </summary>
        public static string Ambassador_Birth_ErrorMessage {
            get {
                return ResourceManager.GetString("Ambassador_Birth_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento.
        /// </summary>
        public static string Ambassador_Birth_Name {
            get {
                return ResourceManager.GetString("Ambassador_Birth_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string Ambassador_City {
            get {
                return ResourceManager.GetString("Ambassador_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Ambassador_Country {
            get {
                return ResourceManager.GetString("Ambassador_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento de identidad o pasaporte.
        /// </summary>
        public static string Ambassador_Dni {
            get {
                return ResourceManager.GetString("Ambassador_Dni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, por cuenta propia.
        /// </summary>
        public static string Ambassador_enum_Organization_1 {
            get {
                return ResourceManager.GetString("Ambassador_enum_Organization_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escuela.
        /// </summary>
        public static string Ambassador_enum_Organization_2 {
            get {
                return ResourceManager.GetString("Ambassador_enum_Organization_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universidad.
        /// </summary>
        public static string Ambassador_enum_Organization_3 {
            get {
                return ResourceManager.GetString("Ambassador_enum_Organization_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organismo Gubernamental.
        /// </summary>
        public static string Ambassador_enum_Organization_4 {
            get {
                return ResourceManager.GetString("Ambassador_enum_Organization_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organización SIN fines de lucro.
        /// </summary>
        public static string Ambassador_enum_Organization_5 {
            get {
                return ResourceManager.GetString("Ambassador_enum_Organization_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organización CON fines de lucro.
        /// </summary>
        public static string Ambassador_enum_Organization_6 {
            get {
                return ResourceManager.GetString("Ambassador_enum_Organization_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Género.
        /// </summary>
        public static string Ambassador_Gender {
            get {
                return ResourceManager.GetString("Ambassador_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organización.
        /// </summary>
        public static string Ambassador_Organization {
            get {
                return ResourceManager.GetString("Ambassador_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la organización.
        /// </summary>
        public static string Ambassador_OrganizationName {
            get {
                return ResourceManager.GetString("Ambassador_OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string Ambassador_Phone {
            get {
                return ResourceManager.GetString("Ambassador_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol en la organización.
        /// </summary>
        public static string Ambassador_RoleInOrganization {
            get {
                return ResourceManager.GetString("Ambassador_RoleInOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string Ambassador_State {
            get {
                return ResourceManager.GetString("Ambassador_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perdí UNA falange de cualquier dedo.
        /// </summary>
        public static string AmputationType_A {
            get {
                return ResourceManager.GetString("AmputationType_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perdí DOS falanges de cualquier dedo.
        /// </summary>
        public static string AmputationType_B {
            get {
                return ResourceManager.GetString("AmputationType_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perdí mis cuatro dedos y tengo un pulgar.
        /// </summary>
        public static string AmputationType_C {
            get {
                return ResourceManager.GetString("AmputationType_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perdí el pulgar y no tengo los dedos. (Poseo hueso carpal).
        /// </summary>
        public static string AmputationType_D {
            get {
                return ResourceManager.GetString("AmputationType_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perdí la mano, no tengo muñeca. (Poseo hueso cúbito y radio pero no carpal).
        /// </summary>
        public static string AmputationType_E {
            get {
                return ResourceManager.GetString("AmputationType_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tengo un muñón a partir del codo y tengo un antebrazo desarrollado. (Huesos cúbito y radio presentes).
        /// </summary>
        public static string AmputationType_F {
            get {
                return ResourceManager.GetString("AmputationType_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perdí el codo y tengo el húmero.
        /// </summary>
        public static string AmputationType_G {
            get {
                return ResourceManager.GetString("AmputationType_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tengo el húmero pero muy poco desarrollado.
        /// </summary>
        public static string AmputationType_H {
            get {
                return ResourceManager.GetString("AmputationType_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string Manage_Code {
            get {
                return ResourceManager.GetString("Manage_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmá la nueva contraseña.
        /// </summary>
        public static string Manage_ConfirmPassword {
            get {
                return ResourceManager.GetString("Manage_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña no coincide.
        /// </summary>
        public static string Manage_ConfirmPassword_ErrorMessage {
            get {
                return ResourceManager.GetString("Manage_ConfirmPassword_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva contraseña.
        /// </summary>
        public static string Manage_NewPassword {
            get {
                return ResourceManager.GetString("Manage_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe tener por lo menos 6 caracteres.
        /// </summary>
        public static string Manage_NewPassword_ErrorMessage {
            get {
                return ResourceManager.GetString("Manage_NewPassword_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de teléfono.
        /// </summary>
        public static string Manage_Number {
            get {
                return ResourceManager.GetString("Manage_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña actual.
        /// </summary>
        public static string Manage_OldPassword {
            get {
                return ResourceManager.GetString("Manage_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De.
        /// </summary>
        public static string Message_From {
            get {
                return ResourceManager.GetString("Message_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario.
        /// </summary>
        public static string Message_Time {
            get {
                return ResourceManager.GetString("Message_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para.
        /// </summary>
        public static string Message_To {
            get {
                return ResourceManager.GetString("Message_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amputación.
        /// </summary>
        public static string Order_AmputationType {
            get {
                return ResourceManager.GetString("Order_AmputationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (si es posible).
        /// </summary>
        public static string Order_Color_Description {
            get {
                return ResourceManager.GetString("Order_Color_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Order_Color_Name {
            get {
                return ResourceManager.GetString("Order_Color_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios.
        /// </summary>
        public static string Order_Comments {
            get {
                return ResourceManager.GetString("Order_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creado.
        /// </summary>
        public static string Order_Date {
            get {
                return ResourceManager.GetString("Order_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courier.
        /// </summary>
        public static string Order_DeliveryCourier {
            get {
                return ResourceManager.GetString("Order_DeliveryCourier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiqueta postal.
        /// </summary>
        public static string Order_DeliveryPostalLabel {
            get {
                return ResourceManager.GetString("Order_DeliveryPostalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string Order_DeliveryTrackingCode {
            get {
                return ResourceManager.GetString("Order_DeliveryTrackingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido #.
        /// </summary>
        public static string Order_Id {
            get {
                return ResourceManager.GetString("Order_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string Order_IdImage {
            get {
                return ResourceManager.GetString("Order_IdImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historial de cambios.
        /// </summary>
        public static string Order_Log {
            get {
                return ResourceManager.GetString("Order_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaños.
        /// </summary>
        public static string Order_OrderSizesModel {
            get {
                return ResourceManager.GetString("Order_OrderSizesModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Cuál?.
        /// </summary>
        public static string Order_ProductType {
            get {
                return ResourceManager.GetString("Order_ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prueba de entrega.
        /// </summary>
        public static string Order_ProofOfDelivery {
            get {
                return ResourceManager.GetString("Order_ProofOfDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Order_Status {
            get {
                return ResourceManager.GetString("Order_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última modificación.
        /// </summary>
        public static string Order_StatusLastUpdated {
            get {
                return ResourceManager.GetString("Order_StatusLastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por tipo:.
        /// </summary>
        public static string OrderFilters_AmputationType {
            get {
                return ResourceManager.GetString("OrderFilters_AmputationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busqueda:.
        /// </summary>
        public static string OrderFilters_SearchTerm {
            get {
                return ResourceManager.GetString("OrderFilters_SearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por estado:.
        /// </summary>
        public static string OrderFilters_Status {
            get {
                return ResourceManager.GetString("OrderFilters_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo requerido.
        /// </summary>
        public static string RequiredErrorMessage {
            get {
                return ResourceManager.GetString("RequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección (solo calle y altura).
        /// </summary>
        public static string User_Address {
            get {
                return ResourceManager.GetString("User_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección (otros datos).
        /// </summary>
        public static string User_Address2 {
            get {
                return ResourceManager.GetString("User_Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Alternativo.
        /// </summary>
        public static string User_AlternativeEmail {
            get {
                return ResourceManager.GetString("User_AlternativeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha inválida.
        /// </summary>
        public static string User_Birth_ErrorMessage {
            get {
                return ResourceManager.GetString("User_Birth_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimiento.
        /// </summary>
        public static string User_Birth_Name {
            get {
                return ResourceManager.GetString("User_Birth_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string User_City {
            get {
                return ResourceManager.GetString("User_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string User_Country {
            get {
                return ResourceManager.GetString("User_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNI o Pasaporte del usuario.
        /// </summary>
        public static string User_Dni {
            get {
                return ResourceManager.GetString("User_Dni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Género.
        /// </summary>
        public static string User_Gender {
            get {
                return ResourceManager.GetString("User_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femenino.
        /// </summary>
        public static string User_Gender_0 {
            get {
                return ResourceManager.GetString("User_Gender_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masculino.
        /// </summary>
        public static string User_Gender_1 {
            get {
                return ResourceManager.GetString("User_Gender_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otro.
        /// </summary>
        public static string User_Gender_2 {
            get {
                return ResourceManager.GetString("User_Gender_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Declara.
        /// </summary>
        public static string User_Gender_3 {
            get {
                return ResourceManager.GetString("User_Gender_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string User_Phone {
            get {
                return ResourceManager.GetString("User_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Documento de Identidad / Pasaporte.
        /// </summary>
        public static string User_ResponsableDni {
            get {
                return ResourceManager.GetString("User_ResponsableDni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido del responsable.
        /// </summary>
        public static string User_ResponsableLastName {
            get {
                return ResourceManager.GetString("User_ResponsableLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del responsable.
        /// </summary>
        public static string User_ResponsableName {
            get {
                return ResourceManager.GetString("User_ResponsableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        public static string User_State {
            get {
                return ResourceManager.GetString("User_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido del usuario.
        /// </summary>
        public static string User_UserLastName {
            get {
                return ResourceManager.GetString("User_UserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del usuario.
        /// </summary>
        public static string User_UserName {
            get {
                return ResourceManager.GetString("User_UserName", resourceCulture);
            }
        }
    }
}
